package com.sma.strategyengine.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Immutable audit log of every signal generated by any strategy instance.
 *
 * BUY / SELL signals are forwarded to Execution Engine; the resulting intentId
 * and execution status are captured here for traceability.
 * HOLD signals are logged with executionStatus = SKIPPED.
 */
@Entity
@Table(name = "signal_record")
@Getter @Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SignalRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "signal_id", unique = true, nullable = false)
    private String signalId;

    /** instanceId of the StrategyInstance that produced this signal. */
    @Column(name = "instance_id", nullable = false)
    private String instanceId;

    @Column(name = "strategy_type", nullable = false)
    private String strategyType;

    @Column(nullable = false)
    private String symbol;

    @Column(nullable = false)
    private String exchange;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Signal signal;

    /** Close price of the candle that triggered this signal. */
    @Column(name = "candle_close")
    private BigDecimal candleClose;

    /** intentId sent to Execution Engine (null for HOLD / failed delivery). */
    @Column(name = "intent_id")
    private String intentId;

    @Enumerated(EnumType.STRING)
    @Column(name = "execution_status", nullable = false)
    private ExecutionStatus executionStatus;

    /** JSON blob with strategy-specific diagnostics (e.g. shortSma, longSma). */
    @Column(columnDefinition = "TEXT")
    private String meta;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    // ─── Enums ────────────────────────────────────────────────────────────────

    public enum Signal { BUY, SELL, HOLD }

    public enum ExecutionStatus {
        /** Intent successfully delivered to Execution Engine. */
        SENT,
        /** Delivery to Execution Engine failed (network/HTTP error). */
        FAILED,
        /** HOLD signal — no intent sent by design. */
        SKIPPED
    }
}
